Neighbors with TF-IDF filter of 10

In [2]:
import networkx as nx
import pandas as pd
import glob

In [2]:
folder_nodes = "nodes_network3.parquet"
folder_edges = "edges_network3.parquet"

nodes_files = glob.glob(folder_nodes)
edges_files = glob.glob(folder_edges)

nodes = pd.concat([pd.read_parquet(file) for file in nodes_files], ignore_index=True)
edges = pd.concat([pd.read_parquet(file) for file in edges_files], ignore_index=True)

In [3]:
edges_filtered = edges[(edges['node1_norm'] == 'judge') | (edges['node2_norm'] == 'judge')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

       node1_norm node2_norm  weight
34894       judge    thought      16
87856        fear      judge      15
29112       judge     social      12
159865     accept      judge      12
135814      judge        man      11
72436       judge        say      11
112570    compare      judge      10
160408      judge       talk      10
165195      judge    opinion      10
174811    instead      judge      10
34345     emotion      judge      10
186989     afraid      judge      10
47733       class      judge      10
6449         base      judge       9
161216    believe      judge       9
98739     feeling      judge       9
77290       judge       part       9
95691      choose      judge       8
115366       high      judge       8
204412      judge        see       8

In [4]:
edges_filtered = edges[(edges['node1_norm'] == 'wrong') | (edges['node2_norm'] == 'wrong')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

        node1_norm node2_norm  weight
74675          say      wrong      37
142230        tell      wrong      28
121621       never      wrong      27
96321      feeling      wrong      25
28139      believe      wrong      22
44933          try      wrong      22
28155       become      wrong      22
73916         talk      wrong      21
10155         give      wrong      21
46498         need      wrong      20
11676       always      wrong      20
26403     decision      wrong      19
23355         butt      wrong      19
159754  understand      wrong      19
5851          come      wrong      19
35458       reason      wrong      18
21935         hurt      wrong      18
180339        ever      wrong      18
114700    thinking      wrong      17
115421      simply      wrong      17

In [5]:
edges_filtered = edges[(edges['node1_norm'] == 'deserve') | (edges['node2_norm'] == 'deserve')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

       node1_norm node2_norm  weight
118625    believe    deserve      17
11867     deserve       hurt      16
8670      deserve  happiness      15
207151    deserve    feeling      14
97065     deserve       pain      13
5617      deserve       tell      11
12916      always    deserve      11
152496    deserve      treat      10
111704    deserve     reason       9
138477    deserve     enough       9
175841    deserve        see       9
77204     deserve   mistakes       9
38765       child    deserve       9
2369      deserve        say       9
10622     deserve       hate       8
69273     deserve      learn       8
17459     deserve    respect       8
1256      deserve       fuck       7
183148    deserve      value       7
180781    deserve    failure       7

In [6]:
edges_filtered = edges[(edges['node1_norm'] == 'fault') | (edges['node2_norm'] == 'fault')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

       node1_norm      node2_norm  weight
141616      blame           fault      20
26989     believe           fault      12
40718       fault           truth      11
41474       fault           voice      10
199157      fault  responsibility      10
76204        ever           fault       8
152697      fault             say       8
200803      fault           woman       7
128822      fault         purpose       7
6163        fault            tell       7
178403       fail           fault       6
169050     choice           fault       6
97089       fault         success       6
100500      fault    relationship       5
61576       fault            fuck       5
41802       adult           fault       5
200186      fault             man       5
100805       date           fault       5
39877       fault         society       5
12700       fault          friend       5

In [7]:
edges_filtered = edges[(edges['node1_norm'] == 'blame') | (edges['node2_norm'] == 'blame')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

       node1_norm      node2_norm  weight
71866     believe           blame      28
198274      blame  responsibility      27
141616      blame           fault      20
201536      blame            live      20
93460       blame         success      20
22347       blame         feeling      20
91653       blame            fear      17
92338      assume           blame      17
155886     belief           blame      16
58018       blame        increase      15
204027      blame          happen      15
49621      afraid           blame      15
51581       blame         compare      15
42070       blame            true      13
89149       blame           truth      12
29765       blame          parent      10
48263       blame            hurt       9
195160      blame           voice       9
190472      blame         purpose       8
37378       blame          choice       8

In [8]:
edges_filtered = edges[(edges['node1_norm'] == 'shame') | (edges['node2_norm'] == 'shame')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

       node1_norm node2_norm  weight
208453    feeling      shame      19
124862    emotion      shame      17
132688       porn      shame      12
74606       shame    thought      10
124384       hurt      shame      10
167981   mistakes      shame      10
109444       fear      shame       9
49199      accept      shame       9
88447         sex      shame       7
57071        pain      shame       7
28808     perfect      shame       7
17435      belief      shame       6
37301         lie      shame       6
17392   emotional      shame       6
175691      shame       tell       6
166030     school      shame       6
188469    failure      shame       6
213944      shame  therapist       5
53507     partner      shame       5
106019      shame      wrong       5

In [9]:
edges_filtered = edges[(edges['node1_norm'] == 'responsibility') | (edges['node2_norm'] == 'responsibility')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

            node1_norm      node2_norm  weight
198274           blame  responsibility      27
68761           choose  responsibility      15
154817          choice  responsibility      14
72353   responsibility         success      13
161275        behavior  responsibility      11
131385           learn  responsibility      11
6749          decision  responsibility      10
98004             book  responsibility      10
182247           power  responsibility      10
140856          become  responsibility      10
199157           fault  responsibility      10
139275            give  responsibility      10
119081             man  responsibility      10
178573       challenge  responsibility      10
132056         failure  responsibility      10
181140            hand  responsibility       9
202540           adult  responsibility       9
183746  responsibility             say       9
135337            fear  responsibility       9
186619         emotion  responsibility       9

In [10]:
edges_filtered = edges[(edges['node1_norm'] == 'worth') | (edges['node2_norm'] == 'worth')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

          node1_norm node2_norm  weight
184068         value      worth      23
30655           need      worth      15
108414       believe      worth      14
13236           give      worth      13
13642         belief      worth      13
29380          human      worth      13
70194           mind      worth      12
201330         spend      worth      12
200274     happiness      worth      12
72368          money      worth      11
53951        certain      worth      11
197381  relationship      worth      11
6277           learn      worth      11
8938           sleep      worth      10
7293         success      worth      10
48156           part      worth      10
204962        result      worth      10
153399          pain      worth      10
78008           task      worth       9
120038           try      worth       9

In [11]:
edges_filtered = edges[(edges['node1_norm'] == 'right') | (edges['node2_norm'] == 'right')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

Empty DataFrame
Columns: [node1_norm, node2_norm, weight]
Index: []

Neighbors with TF-IDF filter of 5

In [13]:
folder_edges = "edges_network4/"

nodes_files = "nodes_network4/nodes.csv"
edges_files = glob.glob(f"{folder_edges}*.csv")

nodes = pd.read_csv(nodes_files)
edges = pd.concat([pd.read_csv(file) for file in edges_files], ignore_index=True)

In [14]:
edges_filtered = edges[(edges['node1_norm'] == 'judge') | (edges['node2_norm'] == 'judge')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

       node1_norm node2_norm  weight
45937        fear      judge      93
244108     accept      judge      86
69964     feeling      judge      78
245934      judge       talk      71
50816       judge       look      67
362469      judge      learn      66
254831      judge    opinion      62
341582    anxiety      judge      61
330968      judge       show      60
372339      judge       stop      60
63941      choose      judge      56
342329      judge    thought      55
107131      judge        see      53
282787       base      judge      52
84932      afraid      judge      52
429710      judge      value      52
358205        act      judge      51
359773    example      judge      49
296261       girl      judge      49
18526       judge       less      49

In [15]:
edges_filtered = edges[(edges['node1_norm'] == 'wrong') | (edges['node2_norm'] == 'wrong')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

          node1_norm node2_norm  weight
422694           say      wrong      56
65233        feeling      wrong      52
420851          talk      wrong      49
367458         first      wrong      46
209370          tell      wrong      44
239869          call      wrong      44
252072         learn      wrong      43
139903           see      wrong      42
282338          come      wrong      41
180731         never      wrong      40
361340           try      wrong      40
342090          keep      wrong      40
328186       believe      wrong      39
85138         accept      wrong      39
197275           ask      wrong      38
361094          fact      wrong      37
408103    everything      wrong      36
294579        always      wrong      36
16499           ever      wrong      35
398015  relationship      wrong      35

In [16]:
edges_filtered = edges[(edges['node1_norm'] == 'should') | (edges['node2_norm'] == 'should')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

Empty DataFrame
Columns: [node1_norm, node2_norm, weight]
Index: []

In [17]:
edges_filtered = edges[(edges['node1_norm'] == 'right') | (edges['node2_norm'] == 'right')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

Empty DataFrame
Columns: [node1_norm, node2_norm, weight]
Index: []

In [18]:
edges_filtered = edges[(edges['node1_norm'] == 'bad') | (edges['node2_norm'] == 'bad')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

Empty DataFrame
Columns: [node1_norm, node2_norm, weight]
Index: []

In [19]:
edges_filtered = edges[(edges['node1_norm'] == 'correct') | (edges['node2_norm'] == 'correct')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

       node1_norm node2_norm  weight
207840    correct       word      20
360095    correct    example      18
8586      correct      learn      17
314167    correct        say      16
154705    correct       true      15
416266    correct       part      14
430362    correct      never      13
57977     correct     happen      13
276533      brain    correct      13
231975    correct       talk      13
342044      begin    correct      13
405533    correct       ever      13
232365   actually    correct      13
106165    correct     create      13
426994    correct    opinion      13
29195    consider    correct      12
23962        body    correct      12
111009    correct    feeling      12
311463       book    correct      12
362991     answer    correct      12

In [20]:
edges_filtered = edges[(edges['node1_norm'] == 'moral') | (edges['node2_norm'] == 'moral')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

Empty DataFrame
Columns: [node1_norm, node2_norm, weight]
Index: []

In [21]:
edges_filtered = edges[(edges['node1_norm'] == 'wrong') | (edges['node2_norm'] == 'wrong')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

          node1_norm node2_norm  weight
422694           say      wrong      56
65233        feeling      wrong      52
420851          talk      wrong      49
367458         first      wrong      46
209370          tell      wrong      44
239869          call      wrong      44
252072         learn      wrong      43
139903           see      wrong      42
282338          come      wrong      41
180731         never      wrong      40
361340           try      wrong      40
342090          keep      wrong      40
328186       believe      wrong      39
85138         accept      wrong      39
197275           ask      wrong      38
361094          fact      wrong      37
408103    everything      wrong      36
294579        always      wrong      36
16499           ever      wrong      35
398015  relationship      wrong      35

Neighbors with TF-IDF filter of 5, "should" and "must" included, all data

In [2]:
folder_edges = "edges_network5/"

nodes_files = "nodes_network5/nodes5.csv"
edges_files = glob.glob(f"{folder_edges}*.csv")

nodes = pd.read_csv(nodes_files)
edges = pd.concat([pd.read_csv(file) for file in edges_files], ignore_index=True)

In [4]:
edges_filtered = edges[(edges['node1_norm'] == 'wrong') | (edges['node2_norm'] == 'wrong')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

        node1_norm node2_norm  weight
64507         tell      wrong     413
147389        ever      wrong     397
269042     believe      wrong     384
214000         say      wrong     381
38539        never      wrong     377
310848      always      wrong     363
308136        give      wrong     342
31099        learn      wrong     324
212773        talk      wrong     323
231570        need      wrong     319
23852   understand      wrong     316
299564        come      wrong     314
283521      reason      wrong     309
183673     feeling      wrong     299
125420       woman      wrong     290
115212    thinking      wrong     280
1699           guy      wrong     280
292477     thought      wrong     276
219842        part      wrong     275
259081        butt      wrong     274

In [5]:
edges_filtered = edges[(edges['node1_norm'] == 'should') | (edges['node2_norm'] == 'should')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

       node1_norm node2_norm  weight
158915       need     should     439
280414      learn     should     384
232880       ever     should     376
64300   important     should     371
196724       give     should     362
268896     should      spend     326
153251     always     should     325
96393         say     should     323
176546       come     should     317
214001      never     should     311
269038     reason     should     308
153113       able     should     302
230025     should       tell     301
51350      should   thinking     298
30914        butt     should     297
238717    instead     should     291
26555     believe     should     291
242968       part     should     277
16545        keep     should     275
266077      first     should     272

In [6]:
edges_filtered = edges[(edges['node1_norm'] == 'must') | (edges['node2_norm'] == 'must')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

Empty DataFrame
Columns: [node1_norm, node2_norm, weight]
Index: []

In [7]:
edges_filtered = edges[(edges['node1_norm'] == 'right') | (edges['node2_norm'] == 'right')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

Empty DataFrame
Columns: [node1_norm, node2_norm, weight]
Index: []

In [8]:
edges_filtered = edges[(edges['node1_norm'] == 'correct') | (edges['node2_norm'] == 'correct')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

Empty DataFrame
Columns: [node1_norm, node2_norm, weight]
Index: []

In [9]:
edges_filtered = edges[(edges['node1_norm'] == 'responsibility') | (edges['node2_norm'] == 'responsibility')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

            node1_norm      node2_norm  weight
256369            need  responsibility     115
42768            learn  responsibility     100
58826             give  responsibility      98
71060             ever  responsibility      92
79119            blame  responsibility      88
183864          accept  responsibility      86
202820          choose  responsibility      83
3174              part  responsibility      83
249052            come  responsibility      79
92754             grow  responsibility      79
93527           parent  responsibility      77
115404         believe  responsibility      77
134378          family  responsibility      77
240221       important  responsibility      76
51650          feeling  responsibility      71
175232          future  responsibility      70
185216          always  responsibility      68
153327  responsibility             say      68
257669  responsibility             two      67
256818             job  responsibility      67

Neighbors with TF-IDF filter of 1, "should" and "must" included, all data

In [4]:
folder_edges = "edges_network6/"

nodes_files = "nodes_network6/part-00000-faf10ccf-7eda-4c2c-950a-d931dff75ee5-c000.csv"
edges_files = glob.glob(f"{folder_edges}*.csv")

nodes = pd.read_csv(nodes_files)
edges = pd.concat([pd.read_csv(file) for file in edges_files], ignore_index=True)

In [12]:
edges_filtered = edges[(edges['node1_norm'] == 'responsibility') | (edges['node2_norm'] == 'responsibility')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

            node1_norm      node2_norm  weight
62027             need  responsibility    3088
255640  responsibility             try    2820
288260  responsibility             say    2557
284970            find  responsibility    2420
303052            butt  responsibility    2338
190958            give  responsibility    2289
127872  responsibility             see    2227
57020             come  responsibility    2208
202374            ever  responsibility    2132
11787             look  responsibility    2011
173068           learn  responsibility    1940
184504            keep  responsibility    1811
319112          always  responsibility    1803
301474           never  responsibility    1775
304758            back  responsibility    1726
10655   responsibility          should    1703
142702           first  responsibility    1634
194316          become  responsibility    1631
314487  responsibility            tell    1617
47248             live  responsibility    1616

In [11]:
edges_filtered = edges[(edges['node1_norm'] == 'wrong') | (edges['node2_norm'] == 'wrong')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

       node1_norm node2_norm  weight
34022         try      wrong   12982
22717         say      wrong   11996
37239        need      wrong   11093
64749        butt      wrong   10450
234403        see      wrong   10172
97089        find      wrong    9874
187502       look      wrong    8884
281436       ever      wrong    8625
106672       come      wrong    8433
116216       give      wrong    8342
197196       tell      wrong    8095
119342     always      wrong    8055
167926      never      wrong    8028
271483     should      wrong    7032
90732        keep      wrong    6993
154824      learn      wrong    6919
21318        talk      wrong    6916
40373       first      wrong    6851
256847       back      wrong    6693
317380    feeling      wrong    6646

In [13]:
edges_filtered = edges[(edges['node1_norm'] == 'shame') | (edges['node2_norm'] == 'shame')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

       node1_norm node2_norm  weight
218678      shame        try    2052
168367       need      shame    1963
143971       find      shame    1703
92651         say      shame    1700
160283    feeling      shame    1654
57061         see      shame    1639
16746        butt      shame    1555
176482       look      shame    1435
176484       come      shame    1421
306445       give      shame    1415
228379       ever      shame    1406
280441      never      shame    1264
184633       back      shame    1212
270361      shame       tell    1206
166752      learn      shame    1176
87833        keep      shame    1165
260547      first      shame    1150
296622      shame       talk    1118
32780      always      shame    1088
255679       long      shame    1056

Neighbors with TF-IDF filter of 1, "should" and "must" included, POS tagging just kept nouns and adjectives

In [4]:
folder_edges = "edges_network7/"

nodes_files = "nodes_network7/part-00000-d8d8c3a0-690f-466e-8a75-641c17892fb1-c000.csv"
edges_files = glob.glob(f"{folder_edges}*.csv")

nodes = pd.read_csv(nodes_files)
edges = pd.concat([pd.read_csv(file) for file in edges_files], ignore_index=True)

In [5]:
edges_filtered = edges[(edges['node1_norm'] == 'shame') | (edges['node2_norm'] == 'shame')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

          node1_norm node2_norm  weight
83789        feeling      shame    1554
68910          first      shame     944
77424          shame        try     832
112933          part      shame     799
62621     everything      shame     792
101070          mind      shame     764
136254  relationship      shame     728
128647          able      shame     723
29278          shame       talk     690
83075         anyone      shame     685
32356          shame      wrong     666
38654          great      shame     664
46212           kind      shame     664
24192            job      shame     660
14190          place      shame     650
66676           long      shame     649
95944            man      shame     639
4463            look      shame     626
34388         little      shame     625
140216         shame       sure     610

In [7]:
edges_filtered = edges[(edges['node1_norm'] == 'wrong') | (edges['node2_norm'] == 'wrong')]
edges_filtered.sort_values('weight', ascending=False)[0:50]

          node1_norm node2_norm  weight
38437        feeling      wrong    6178
103643    everything      wrong    6067
90822          first      wrong    5887
87990            try      wrong    5384
93069   relationship      wrong    4831
130384          mind      wrong    4653
141084        reason      wrong    4393
112827          part      wrong    4242
85765           sure      wrong    4194
109354          talk      wrong    4184
32092            job      wrong    4152
70842           long      wrong    4152
90146          great      wrong    4149
58861         anyone      wrong    4144
9846            kind      wrong    4084
110725         happy      wrong    4062
93004         social      wrong    3948
4893            able      wrong    3923
100044        little      wrong    3791
7026           place      wrong    3762
9172            look      wrong    3671
84386            guy      wrong    3611
130443           end      wrong    3600
71619            man      wrong    3561
84381           read      wrong    3485
40506      important      wrong    3457
71592           stop      wrong    3420
72336         friend      wrong    3370
107988        school      wrong    3367
119904          last      wrong    3153
77326         family      wrong    3153
88009           fact      wrong    3113
26921          learn      wrong    2964
68160          woman      wrong    2947
114906       example      wrong    2945
39817           real      wrong    2888
133947          girl      wrong    2860
141083          book      wrong    2789
112799           big      wrong    2677
30696           shit      wrong    2665
32129         moment      wrong    2621
121936         whole      wrong    2609
17752          sense      wrong    2583
16976           easy      wrong    2566
88739          money      wrong    2552
82918           head      wrong    2540
109309          true      wrong    2487
123330          give      wrong    2465
123364        parent      wrong    2443
26951           high      wrong    2393

In [8]:
edges_filtered = edges[(edges['node1_norm'] == 'moral') | (edges['node2_norm'] == 'moral')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

Empty DataFrame
Columns: [node1_norm, node2_norm, weight]
Index: []

In [9]:
edges_filtered = edges[(edges['node1_norm'] == 'duty') | (edges['node2_norm'] == 'duty')]
edges_filtered.sort_values('weight', ascending=False)[0:20]

Empty DataFrame
Columns: [node1_norm, node2_norm, weight]
Index: []